# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemploApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='dni',
            field=models.IntegerField(default=True),
        ),
    ]
